### ISSUE TITLE
In edit view, (optionally?) show strikethrough style [enhancement]

### ISSUE THREAD

**Issue by pydolan** [atom/language-gfm#142]
Similar to how bold and italics are shown in the edit view, it would be nice to show font with strikethroughs.  Perhaps have an option for this feature?

![screen shot 2016-02-23 at 10 15 01 am](https://cloud.githubusercontent.com/assets/467780/13255909/67e2617c-da16-11e5-8103-81955ee1827f.png)

**Comment by 50Wliu** [comment]
@pydolan Please re-open this on the syntax theme you're using (one-dark-syntax perhaps?), as each theme determines how everything is displayed.

**Comment by pydolan** [comment]
Thanks!  I see now that language-gfm is indeed adding a css class, so I just customized the style for myself via Atom's styles.css:
```less
atom-text-editor::shadow {
  // settting strikethrough style in markdown
  .source.gfm .strike {
    text-decoration: line-through;
  }
}
```
