### ISSUE TITLE
GFM Syntax highlighting broken

### ISSUE THREAD

**Issue by plaindocs** [atom/language-gfm#189]
The following markdown code breaks highlighting

    ```yaml
    notifications:
    slack:
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%    {branch} by %{author} %{result} in %{duration}" 
    ```

### Steps to Reproduce

**Reproduces how often:** 100%

### Versions

You can get this information from copy and pasting the output of `atom --version` and `apm --version` from the command line. Also, please include the OS and what version of the OS you're running.

Atom    : 1.11.2
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0

On Linux Antergos 
![screenshot from 2017-03-03 13-46-35](https://cloud.githubusercontent.com/assets/95874/23541118/f6e1ac48-0017-11e7-87ec-82e2efbd6921.png)

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.
